uicc0 = {
  imsi = "999700000000001";
  key  = "465B5CE8B199B49FAA5F0A2EE238A6BC";
  opc  = "E8ED289DEBA952E4283B54E88E6183CA";
  pdu_sessions = ({ dnn = "internet"; nssai_sst = 1; });
}

rfsimulator = (
{
  serveraddr = "10.200.1.1";
  serverport = 4043;
  options    = ();
  modelname  = "AWGN";
  IQfile     = "/tmp/rfsimulator.iqs";
}
);
